name: Dev Build (JDK 21)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # запуск руками при необходимости

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven      # кеширует ~/.m2/repository

      - name: Quick Check
        run: mvn -q verify -Pdev -pl labs/lab00-*

      - name: Build & test with Maven (dev profile)
        run: mvn -B verify -Pdev