name: Native Build (GraalVM 24)

on:
  pull_request:
    branches: [ main ]   # чтобы не тормозить каждый push в feature-ветки
    paths:
      - '**/lab*/**'     # гоняем CI только для лабораторных модулей
      - 'project/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  native-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM 24 CE (with Native Image)
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: '24'
          cache: maven
          check-latest: true
          # автомат. ставит Native Image; если хочется вручную:
          #  - run: gu install native-image

      - name: Install Native Image component
        run: |
          echo "Installing native-image…"
          gu install native-image

      - name: Show java -version
        run: java -version

      - name: Build & test with Maven (native profile)
        run: mvn -B verify -Pnative

      # опционально: загружаем артефакт с нативным бинарем
      - name: Upload native executable
        if: |
          startsWith(github.event.pull_request.head.ref, 'lab')
        uses: actions/upload-artifact@v4
        with:
          name: native-image
          path: |
            **/target/*-runner
