name: Native Build (GraalVM CE 24 / JDK 21)

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/lab*/**'
      - 'project/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  native-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM 24 with Native Image
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: '21'       # ← GraalVM 24 + JDK 21
          cache: maven
          components: native-image

      - run: java -version

      - name: Build & test (native profile)
        run: mvn -B verify -Pnative

      - name: Upload native executable
        if: startsWith(github.event.pull_request.head.ref, 'lab')
        uses: actions/upload-artifact@v4
        with:
          name: native-image
          path: "**/target/*-runner"
